[package]
name = "api-identity"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-convert.workspace = true
api-helper.workspace = true
async-trait = "0.1"
chirp-workflow.workspace = true
chirp-client.workspace = true
rivet-operation.workspace = true
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
lazy_static = "1.4"
prost = "0.10"
rivet-api.workspace = true
rivet-cache.workspace = true
rivet-claims.workspace = true
rivet-health-checks.workspace = true
rivet-pools.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.40" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
url = "2.2.2"
util-mm.workspace = true
uuid = { version = "1", features = ["v4"] }

cdn-namespace-get.workspace = true
game-get.workspace = true
game-namespace-get.workspace = true
game-namespace-resolve-url.workspace = true
game-resolve-namespace-id.workspace = true
job-run.workspace = true
mm-config-lobby-group-resolve-version.workspace = true
mm-config-version-get.workspace = true
mm-lobby-get.workspace = true
region-get.workspace = true
team-recommend.workspace = true
token-create.workspace = true
token-get.workspace = true
token-revoke.workspace = true
upload-prepare.workspace = true
user.workspace = true
user-avatar-upload-complete.workspace = true
user-identity-get.workspace = true
rivet-config.workspace = true
rivet-env.workspace = true

[dev-dependencies]
rivet-connection.workspace = true
rivet-identity.workspace = true
util-mm.workspace = true
regex = "1.4"
rand = "0.8"

cdn-namespace-domain-create.workspace = true
cloud-namespace-token-development-create.workspace = true
faker-build.workspace = true
faker-game.workspace = true
faker-game-namespace.workspace = true
faker-game-version.workspace = true
faker-region.workspace = true
faker-user.workspace = true
