[package]
name = "user-worker"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-convert.workspace = true
chirp-client.workspace = true
chirp-workflow.workspace = true
chirp-worker.workspace = true
chrono = "0.4"
lazy_static = "1.4.0"
rivet-health-checks.workspace = true
rivet-metrics.workspace = true
rivet-runtime.workspace = true
game-get.workspace = true
game-namespace-get.workspace = true
team-get.workspace = true
team-member-list.workspace = true
upload-list-for-user.workspace = true
user.workspace = true
user-identity-delete.workspace = true
rivet-config.workspace = true

[dev-dependencies]
chirp-worker.workspace = true

faker-user.workspace = true
upload-get.workspace = true
upload-prepare.workspace = true
