[package]
name = "api-group"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-convert.workspace = true
api-helper.workspace = true
async-trait = "0.1"
chirp-client.workspace = true
chirp-workflow.workspace = true
rivet-operation.workspace = true
chrono = "0.4"
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
lazy_static = "1.4"
prost = "0.10"
rivet-api.workspace = true
rivet-cache.workspace = true
rivet-claims.workspace = true
rivet-group-server.workspace = true
rivet-health-checks.workspace = true
rivet-pools.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.40" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
url = "2.2.2"
uuid = { version = "1", features = ["v4"] }

game-get.workspace = true
game-resolve-namespace-id.workspace = true
team-avatar-upload-complete.workspace = true
team-get.workspace = true
team-invite-get.workspace = true
team-join-request-list.workspace = true
team-member-count.workspace = true
team-member-list.workspace = true
team-profile-validate.workspace = true
team-recommend.workspace = true
team-user-ban-get.workspace = true
team-user-ban-list.workspace = true
token-revoke.workspace = true
upload-prepare.workspace = true
user.workspace = true
user-identity-get.workspace = true
rivet-config.workspace = true
rivet-env.workspace = true

[dev-dependencies]
rivet-connection.workspace = true
rivet-group.workspace = true
rand = "0.8"

faker-user.workspace = true
