[package]
name = "user"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.198", features = ["derive"] }
chirp-workflow.workspace = true

cluster.workspace = true
server-spec.workspace = true
linode.workspace = true
rivet-config.workspace = true
