[package]
name = "api-auth"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
api-helper.workspace = true
async-trait = "0.1"
captcha-verify.workspace = true
chirp-client.workspace = true
chirp-workflow.workspace = true
chrono = "0.4"
email-verification-complete.workspace = true
email-verification-create.workspace = true
headers = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
lazy_static = "1.4"
prost = "0.10"
rivet-api.workspace = true
rivet-auth-server.workspace = true
rivet-cache.workspace = true
rivet-claims.workspace = true
rivet-config.workspace = true
rivet-convert.workspace = true
rivet-env.workspace = true
rivet-health-checks.workspace = true
rivet-operation.workspace = true
rivet-pools.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
token-create.workspace = true
token-revoke.workspace = true
tokio = { version = "1.40" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }
url = "2.2.2"
user.workspace = true
user-identity-create.workspace = true
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
rivet-auth.workspace = true
rivet-connection.workspace = true

faker-user.workspace = true
debug-email-res.workspace = true
user-identity-get.workspace = true

