[package]
name = "api-cloud"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
api-helper.workspace = true
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
chirp-client.workspace = true
chirp-workflow.workspace = true
chrono = "0.4"
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
lazy_static = "1.4"
prost = "0.10"
rand = "0.8"
reqwest = "0.11"
rivet-api.workspace = true
rivet-cache.workspace = true
rivet-claims.workspace = true
rivet-convert.workspace = true
rivet-health-checks.workspace = true
rivet-operation.workspace = true
rivet-pools.workspace = true
s3-util.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.40" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }
url = "2.2.2"
util-job.workspace = true
util-mm.workspace = true
util-team.workspace = true
uuid = { version = "1", features = ["v4"] }

build-create.workspace = true
build-get.workspace = true
build-list-for-game.workspace = true
cdn-namespace-auth-user-remove.workspace = true
cdn-namespace-auth-user-update.workspace = true
cdn-namespace-domain-create.workspace = true
cdn-namespace-domain-remove.workspace = true
cdn-ns-auth-type-set.workspace = true
cdn-ns-enable-domain-public-auth-set.workspace = true
cdn-site-create.workspace = true
cdn-site-get.workspace = true
cdn-site-list-for-game.workspace = true
cf-custom-hostname-list-for-namespace-id.workspace = true
cloud-device-link-create.workspace = true
cloud-game-config-create.workspace = true
cloud-game-config-get.workspace = true
cloud-game-token-create.workspace = true
cloud-namespace-create.workspace = true
cloud-namespace-get.workspace = true
cloud-namespace-token-development-create.workspace = true
cloud-namespace-token-public-create.workspace = true
cloud-version-get.workspace = true
cloud-version-publish.workspace = true
cluster.workspace = true
custom-user-avatar-list-for-game.workspace = true
custom-user-avatar-upload-complete.workspace = true
game-banner-upload-complete.workspace = true
game-create.workspace = true
game-get.workspace = true
game-list-for-team.workspace = true
game-logo-upload-complete.workspace = true
game-namespace-create.workspace = true
game-namespace-get.workspace = true
game-namespace-list.workspace = true
game-namespace-validate.workspace = true
game-namespace-version-history-list.workspace = true
game-namespace-version-set.workspace = true
game-resolve-namespace-id.workspace = true
game-token-development-validate.workspace = true
game-validate.workspace = true
game-version-get.workspace = true
game-version-list.workspace = true
game-version-validate.workspace = true
job-run.workspace = true
mm-config-lobby-group-get.workspace = true
mm-config-lobby-group-resolve-version.workspace = true
mm-config-namespace-config-set.workspace = true
mm-config-namespace-config-validate.workspace = true
mm-config-version-get.workspace = true
mm-lobby-get.workspace = true
mm-lobby-history.workspace = true
mm-lobby-list-for-namespace.workspace = true
mm-lobby-player-count.workspace = true
mm-lobby-runtime-aggregate.workspace = true
mm-player-count-for-namespace.workspace = true
job-log-read.workspace = true
region-get.workspace = true
region-list-for-game.workspace = true
team-get.workspace = true
team-member-count.workspace = true
team-validate.workspace = true
tier.workspace = true
token-create.workspace = true
token-revoke.workspace = true
upload-complete.workspace = true
upload-file-list.workspace = true
upload-get.workspace = true
upload-prepare.workspace = true
user.workspace = true
user-get.workspace = true
user-identity-get.workspace = true
user-team-list.workspace = true
rivet-config.workspace = true
rivet-env.workspace = true

[dev-dependencies]
rand = "0.8"
rivet-connection.workspace = true

faker-region.workspace = true
faker-team.workspace = true
token-create.workspace = true
user-identity-create.workspace = true
