[package]
name = "rivet-convert"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client.workspace = true
chirp-workflow.workspace = true
rivet-operation.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
types-proto.workspace = true
util-mm.workspace = true

cdn-namespace-get.workspace = true
cluster.workspace = true
game-get.workspace = true
game-namespace-get.workspace = true
game-namespace-list.workspace = true
game-resolve-namespace-id.workspace = true
game-token-development-validate.workspace = true
game-validate.workspace = true
game-version-validate.workspace = true
job-run.workspace = true
mm-lobby-player-count.workspace = true
mm-lobby-runtime-aggregate.workspace = true
mm-player-count-for-namespace.workspace = true
region-get.workspace = true
region-list-for-game.workspace = true
region-resolve.workspace = true
team-get.workspace = true
team-member-count.workspace = true
team-profile-validate.workspace = true
team-validate.workspace = true
tier.workspace = true
user.workspace = true
user-get.workspace = true
user-identity-get.workspace = true

rivet-api.workspace = true
rivet-group-server.workspace = true
rivet-portal-server.workspace = true
rivet-config.workspace = true
